

all: CANTERA DRGEP LUMPING MAIN OPTIMISATION READ_WRITE TOOLS EMST

CANTERA:
             
	cd cantera; make

DRGEP:

	cd drgep; make
      
LUMPING:

	cd lumping; make
      
MAIN:
   
	cd main; make
      
OPTIMISATION:
   
	cd optimisation; make
      
READ_WRITE:
   
	cd read_write; make
      
TOOLS:
     
	cd tools; make

EMST:
     
	cd emst; make

        

clean:

	cd cantera; make clean
	cd drgep; make clean
	cd lumping; make clean
	cd main; make clean
	cd optimisation; make clean
	cd read_write; make clean
	cd tools; make clean
	cd emst; make clean



